# -*- coding: utf-8 -*-
"""Python Project 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lECPCSjVk-XJV8FgwX3jvJDOPME84H1e

**Project Information**

**Project - 02**
* Project Title: Data Visualization (Dashboard) with Python using Pandas, Numpy, Matplotlib & Streamlit Libraries
* Sumitted By: Vibhavari Saran(055055)
* Program: PGDM-BDA-05
* Facult: Prof Amarnath Mitra
* Subject: Data Explration & Visualization using Python(DEVP)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import streamlit as st
import seaborn as sns

file_path = (r"C:\Users\DELL\Downloads\archive (1)\Imports_Exports_Dataset.csv")
df = pd.read_csv(file_path)
df = pd.DataFrame(df)
df

# Display the Dimensions of Data.
df.shape

# Display Data Information.
df.info

# Createing an Unique Sample of 3001 Records using Student Roll Number as Random State.
sample= df.sample(n=3001, random_state=55055)
sample

# 1]What is the relationship between the quantity of goods and their total value for exports and imports?
# Scatter Plot: Quantity vs Value (Import/Export)
# X-axis: Quantity
# Y-axis: Value
plt.figure(figsize=(10, 6))
sns.scatterplot(data=sample, x='Quantity', y='Value', hue='Import_Export')
plt.title('Quantity vs Value (Import/Export)')
plt.show()

# 2]How do the total values of imports and exports change over time?
# Line Graph: Total Value of Imports and Exports Over Time
sample['Date'] = pd.to_datetime(sample['Date'])
sample['Month'] =sample['Date'].dt.to_period('M')
monthly_data = sample.groupby(['Month', 'Import_Export'])['Value'].sum().unstack()
monthly_data.plot(kind='line', figsize=(10,6), marker='o')
plt.title('Imports vs Exports Over Time')
plt.xlabel('Month')
plt.ylabel('Transaction Value')
plt.show()

# 3]What is the distribution of product values by category?
# Box-Whisker Plot: Product Value Distribution by Category
# X-axis: Category
# Y-axis: Value
plt.figure(figsize=(12, 6))
sns.boxplot(data=sample, x='Category', y='Value')
plt.title('Product Value Distribution by Category')
plt.xticks(rotation=45)
plt.show()

# 4]Which country exports the highest quantity of goods?
# Bar Chart: Country with the Highest Quantity of Exports
# X-axis: Country
# Y-axis: Quantity (sum for each country)
sample_export = sample[sample['Import_Export'] == 'Export']
sample_export_grouped = sample_export.groupby('Country')['Quantity'].sum().reset_index()
top_10_exporting_countries = sample_export_grouped.sort_values(by='Quantity', ascending=False).head(10)
plt.figure(figsize=(12, 6))
sns.barplot(data=top_10_exporting_countries, x='Country', y='Quantity')
plt.title('Top 10 Countries by Export Quantity')
plt.xticks(rotation=45)
plt.show()

# 5]How is the distribution of the weight of goods shipped?
#  Histogram: Distribution of Shipping Weight
# X-axis: Weight
# Y-axis: Frequency
plt.figure(figsize=(10, 6))
sns.histplot(sample['Weight'], bins=20, kde=True)
plt.title('Distribution of Shipping Weight')
plt.show()

# 6]What is the distribution of the different shipping methods used?
# Pie Chart: Distribution of Shipping Methods
# Labels: Shipping Method
# Values: Count of each shipping method used
shipping_method_counts = sample['Shipping_Method'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(shipping_method_counts, labels=shipping_method_counts.index, autopct='%1.1f%%')
plt.title('Distribution of Shipping Methods')
plt.show()

# 7]How does the weight of goods correlate with their quantity for different product categories?
# Scatter Plot: Weight vs Quantity (Category)
# X-axis: Weight
# Y-axis: Quantity
# Hue/Color: Category
plt.figure(figsize=(10, 6))
sns.scatterplot(data=sample, x='Weight', y='Quantity', hue='Category')
plt.title('Weight vs Quantity by Category')
plt.show()

# 8]What is the correlation between numerical variables like Quantity, Value, Weight, and Customs Code for all transactions?
numeric_cols = ['Quantity', 'Value', 'Weight', 'Customs_Code']
correlation_matrix = sample[numeric_cols].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Between Numerical Variables')
plt.show()

# 9] Which product categories account for the highest total value of exports?
# ar Chart: Highest Value of Exported Product Categories
# X-axis: Product Category
# Y-axis: Total Value (sum)
sample_export_grouped = sample_export.groupby('Category')['Value'].sum().reset_index().sort_values(by='Value', ascending=False)
plt.figure(figsize=(12, 6))
sns.barplot(data=sample_export_grouped, x='Category', y='Value')
plt.title('Top Export Product Categories by Value')
plt.xticks(rotation=45)
plt.show()

# 10]What is the distribution of product values across different product categories?
# Histogram: Distribution of Product Values by Category
# X-axis: Value
# Y-axis: Frequency
# Hue/Color: Category
plt.figure(figsize=(10, 6))
sns.histplot(data=sample, x='Value', hue='Category', bins=20, kde=True)
plt.title('Distribution of Product Values by Category')
plt.show()

# 11]What percentage of transactions is represented by each country?
# Pie Chart: Distribution of Transactions by Country
# Labels: Country
# Values: Number of Transactions
country_counts = sample['Country'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(country_counts, labels=country_counts.index, autopct='%1.1f%%')
plt.title('Distribution of Transactions by Country')
plt.show()

# 12]What is the distribution of shipping weights for different shipping methods?
# Box-Whisker Plot: Weight Distribution by Shipping Method
# X-axis: Shipping Method
# Y-axis: Weight
# Grouping: Shipping Method
plt.figure(figsize=(10, 6))
sns.boxplot(data=sample, x='Shipping_Method', y='Weight')
plt.title('Weight Distribution by Shipping Method')
plt.show(1)

# 13]What are the top 5 customers by the value of goods purchased?
# Bar Chart: Top 5 Customers by Total Purchase Value
# X-axis: Customer
# Y-axis: Total Value (sum)
sample_customers = sample.groupby('Customer')['Value'].sum().reset_index().sort_values(by='Value', ascending=False).head(5)
plt.figure(figsize=(10, 6))
sns.barplot(data=sample_customers, x='Customer', y='Value')
plt.title('Top 5 Customers by Total Purchase Value')
plt.show()

# 14]What is the distribution of customs codes used in transactions?
# Histogram: Distribution of Customs Codes
# X-axis: Customs Code
# Y-axis: Frequency
plt.figure(figsize=(10, 6))
sns.histplot(sample['Customs_Code'], bins=20, kde=True)
plt.title('Distribution of Customs Codes')
plt.show()

# 15]What is the percentage distribution of payment terms used (e.g., Prepaid, Cash on Delivery, Net 60)?
# Pie Chart: Distribution of Payment Terms
# Labels: Payment Terms
# Values: Count of each payment term
payment_terms_counts = sample['Payment_Terms'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(payment_terms_counts, labels=payment_terms_counts.index, autopct='%1.1f%%')
plt.title('Distribution of Payment Terms')
plt.show()

# 16]How does the total weight of goods exported and imported change over the years?
# Line Graph: Total Weight of Exports and Imports Over Time
# X-axis: Date (yearly/quarterly)
# Y-axis: Weight
sample['Date'] = pd.to_datetime(sample['Date'])
sample['Month'] = sample['Date'].dt.to_period('M')
monthly_data = sample.groupby(['Month', 'Import_Export'])['Value'].sum().unstack()
monthly_data.plot(kind='line', figsize=(10,6), marker='o')
plt.title('Imports vs Exports Over Time')
plt.xlabel('Month')
plt.ylabel('Transaction Value')
plt.show()

# 17]What is the distribution of values for transactions based on the payment terms?
# Box-Whisker Plot: Value Distribution by Payment Terms
# X-axis: Payment Terms
# Y-axis: Value
# Grouping: Payment Terms
plt.figure(figsize=(10, 6))
sns.boxplot(data=sample, x='Payment_Terms', y='Value')
plt.title('Value Distribution by Payment Terms')
plt.show()

# 18]Which are the top 5 suppliers by the number of transactions completed?
# Bar Chart: Top 5 Suppliers by Transaction Count
# X-axis: Supplier
# Y-axis: Number of Transactions
sample_suppliers = sample.groupby('Supplier')['Transaction_ID'].count().reset_index().sort_values(by='Transaction_ID', ascending=False).head(5)
plt.figure(figsize=(10, 6))
sns.barplot(data=sample_suppliers, x='Supplier', y='Transaction_ID')
plt.title('Top 5 Suppliers by Transaction Count')
plt.xticks(rotation=45)
plt.show()

# 19]What is the distribution of export versus import transactions in the dataset?
# Pie Chart: Import vs Export Transactions
# Labels: Import/Export
# Values: Count of transactions\
import_export_counts = sample['Import_Export'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(import_export_counts, labels=import_export_counts.index, autopct='%1.1f%%')
plt.title('Import vs Export Transactions')
plt.show()

# 20]What is the relationship between the total value of exports/imports and shipping methods across different countries?
last_5_countries = sample['Country'].unique()[-5:]
sample_last_5_countries = sample[sample['Country'].isin(last_5_countries)]
heatmap_data = sample_last_5_countries.pivot_table(values='Quantity', index='Country', columns='Category', aggfunc='sum')
plt.figure(figsize=(10, 6))
sns.heatmap(heatmap_data, cmap='Blues', annot=True, fmt='.1f')
plt.title('Quantity of Goods by Product Category and Last 5 Countries')
plt.xticks(rotation=45)
plt.show()